<%@ Page Language="C#" AutoEventWireup="true" CodeFile="default.aspx.cs" Inherits="CMSModules_ThinkgateAdmin_default" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <style type="text/css">
.classname {
	-moz-box-shadow:inset 0px 1px 0px 0px #ffffff;
	-webkit-box-shadow:inset 0px 1px 0px 0px #ffffff;
	box-shadow:inset 0px 1px 0px 0px #ffffff;
	background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #ededed), color-stop(1, #dfdfdf) );
	background:-moz-linear-gradient( center top, #ededed 5%, #dfdfdf 100% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#ededed', endColorstr='#dfdfdf');
	background-color:#ededed;
	-moz-border-radius:6px;
	-webkit-border-radius:6px;
	border-radius:6px;
	border:1px solid #dcdcdc;
	display:inline-block;
	color:#777777;
	font-family:arial;
	font-size:15px;
	font-weight:bold;
	padding:6px 24px;
	text-decoration:none;
	text-shadow:1px 1px 0px #ffffff;
}.classname:hover {
	background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #dfdfdf), color-stop(1, #ededed) );
	background:-moz-linear-gradient( center top, #dfdfdf 5%, #ededed 100% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#dfdfdf', endColorstr='#ededed');
	background-color:#dfdfdf;
}.classname:active {
	position:relative;
	top:1px;
}
/* This imageless css button was generated by CSSButtonGenerator.com */
</style>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    <fieldset><legend>Sample Control:</legend>
        <asp:Button CssClass="classname" ID="btnGetTime" runat="server" Text="Get Time" OnClick="btnGetTime_Click" />
        &nbsp&nbsp&nbsp<asp:Label ID="lblTime" runat="server" Text=""></asp:Label>
        </fieldset>
    
    </div>
        <br /><br />
        <div style="border: 0px solid #000000;">
            <fieldset><legend>Administrator Controls:</legend><center>
        <asp:Button CssClass="classname" ID="Button1" runat="server" OnClick="ImportRoles_Click" Text="Import Roles From E3" /><br /><br />
        <asp:Button CssClass="classname" ID="Button2" runat="server" Text="Import Users And Associate Roles From E3" OnClick="Button2_Click" />
                <br />(WARNING:  THIS CAN TAKE UP TO 5 MINUTES FOR USER BASES OF 10,000)
                <br /><br /></center>
                <fieldset><legend>Results:</legend>
                    <asp:Label ID="Response" runat="server" Text=""></asp:Label><br />
                    </fieldset>
        </fieldset>
                </div>
            
            
    </form>
</body>
</html>
